apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota
  namespace: karakeep
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "4"
    limits.memory: 5Gi
    pods: "10"
    persistentvolumeclaims: "5"
