apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota
  namespace: ghost-dev
spec:
  hard:
    requests.cpu: "500m"
    requests.memory: 2Gi
    limits.cpu: "2"
    limits.memory: 4Gi
    pods: "10"
    persistentvolumeclaims: "5"
