apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota
  namespace: velero
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 2Gi
    limits.cpu: "4"
    limits.memory: 4Gi
    pods: "15"
    persistentvolumeclaims: "5"
