apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota
  namespace: uptime-kuma
spec:
  hard:
    requests.cpu: "500m"
    requests.memory: 512Mi
    limits.cpu: "1"
    limits.memory: 2Gi
    pods: "5"
    persistentvolumeclaims: "5"
