apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota
  namespace: arr-stack
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 6Gi
    limits.cpu: "22"
    limits.memory: 24Gi
    pods: "30"
    persistentvolumeclaims: "20"
