apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 2Gi
    limits.cpu: "5"
    limits.memory: 6Gi
    pods: "15"
    persistentvolumeclaims: "5"
