apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota
  namespace: invoicetron-dev
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 2Gi
    limits.cpu: "4"
    limits.memory: 6Gi
    pods: "10"
    persistentvolumeclaims: "5"
